#!/usr/bin/env python3
"""
16_supplementary_table.py

Generate a LaTeX supplementary table (Table B1) containing all 47
Orbital high-mass dark-companion candidates ranked by K1_edge.

Merges recovered 19-digit source IDs from script 15 with the full
comparison data from script 10.

Output:  paper/table_population_full.tex
"""

import json
import os

REPO = os.path.join(os.path.dirname(__file__), "..")
COMPARISON = os.path.join(REPO, "scripts", "outputs", "orbital_bh_comparison.json")
RECOVERED = os.path.join(REPO, "results", "recovered_source_ids.json")
OUTPUT = os.path.join(REPO, "paper", "table_population_full.tex")

THIS_SOURCE = "4277855016732107520"


def main():
    with open(COMPARISON, encoding="utf-8") as f:
        comp = json.load(f)
    with open(RECOVERED, encoding="utf-8") as f:
        rec = json.load(f)

    # Build lookup: approx_id -> true_id
    id_map = {r["approx_id"]: r["true_id"] for r in rec["recovered"]}

    candidates = comp["all_candidates"]  # already sorted by K1 desc

    lines = []
    lines.append(r"% Auto-generated by scripts/16_supplementary_table.py")
    lines.append(r"% Full 47-source catalogue of Orbital high-mass dark-companion candidates")
    lines.append(r"\begin{table*}")
    lines.append(r"\centering")
    lines.append(r"\caption{All 47 Gaia DR3 \texttt{Orbital} high-mass dark-companion")
    lines.append(r"candidates ($M_2 > 5\,\Msun$) ranked by predicted edge-on")
    lines.append(r"radial-velocity semi-amplitude $K_{1,\rm edge}$")
    lines.append(r"(Equation~\ref{eq:K1}).  Quality tiers follow")
    lines.append(r"\citet{GaiaNSS2023}: Gold requires GOF~$< 25$,")
    lines.append(r"significance~$> 20\sigma$, and $\sigma_e < 0.1$;")
    lines.append(r"Silver relaxes one criterion; Bronze relaxes two or more.")
    lines.append(r"\emph{Rankings reflect observational accessibility and are not")
    lines.append(r"evidence for the reality of any individual solution.}")
    lines.append(r"The target of this paper is highlighted in bold.}")
    lines.append(r"\label{tab:population_full}")
    lines.append(r"\begin{tabular}{rlrrrrrrrll}")
    lines.append(r"\toprule")
    lines.append(
        r"Rank & Gaia DR3 source ID & $G$ & $P$ & $e$ & $M_2$ & "
        r"$K_{1,\rm edge}$ & $\sigma_{\rm NSS}$ & Tier & Hem.\ & Annual \\"
    )
    lines.append(
        r" & & (mag) & (d) & & ($\Msun$) & (km\,s$^{-1}$) & & & & flag \\"
    )
    lines.append(r"\midrule")

    for rank, c in enumerate(candidates, 1):
        approx = c["source_id"]
        true_id = id_map.get(approx, approx)
        is_target = true_id == THIS_SOURCE

        g = f"{c['G']:.2f}"
        p = f"{c['period_d']:.0f}"
        ecc = f"{c['ecc']:.2f}"
        m2 = f"{c['M2_msun']:.1f}"
        k1 = f"{c['K1_pred_kms']:.1f}"
        sig = f"{c['nss_sig']:.1f}"
        tier = c["tier"].capitalize()
        hem = c["accessible"]
        annual = r"$\checkmark$" if c["annual_flag"] else ""

        fields = [
            str(rank), true_id, g, p, ecc, m2, k1, sig, tier, hem, annual
        ]

        if is_target:
            row = " & ".join(r"\textbf{" + f + "}" for f in fields)
        else:
            row = " & ".join(fields)

        lines.append(row + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written {len(candidates)}-row supplementary table to {OUTPUT}")


if __name__ == "__main__":
    main()
